fixed IDAM-428: auth code inactive check, improved logging
companieshouse/forgerock-cloud-config pull request #93
Opened 2021-04-26 16:28 UTC by matteoformica-amido

2021-04-26 17:23 UTC, Irrelon requested changes

2021-04-26 17:23 UTC, Irrelon commented on config/am-scripts/scripts-content/ch-join-company-create-relationship.js
>              'companyNumber': JSON.parse(companyData).name
Is this required and if so, is this supposed to be outputting companyData.name instead of company number?

2021-04-26 19:22 UTC, steveclewer-amido approved these changes

2021-04-27 08:47 UTC, Irrelon requested changes

2021-04-27 08:47 UTC, Irrelon commented on config/am-scripts/scripts-content/ch-fetch-company-info.js
> +                    'companyNumber': { number: companyNumber }
Minor error here, should be  `"company": {number: companyNumber}`, same as line 190

2021-04-27 10:55 UTC, Irrelon approved these changes

2021-04-27 10:55 UTC, merged